# Generated by Django 4.2.2 on 2023-07-21 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("manga", "0016_alter_chapter_chapter_number"),
        ("users", "0002_alter_customuser_avatar_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="dropped",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="favorite",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="planned",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="readed",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="reading",
        ),
        migrations.CreateModel(
            name="MangaUserList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "list_type",
                    models.CharField(
                        choices=[
                            ("reading", "Читаю"),
                            ("planned", "В планах"),
                            ("dropped", "Брошено"),
                            ("readed", "Прочитано"),
                            ("favorite", "Любимые"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "manga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="manga.manga"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manga_list",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
