# Generated by Django 4.2.2 on 2023-07-21 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_customuser_dropped_remove_customuser_favorite_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mangauserlist",
            name="comment",
            field=models.TextField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name="mangauserlist",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 21, 12, 7, 47, 341733)
            ),
        ),
    ]
