# Generated by Django 4.2.2 on 2023-06-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manga", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="manga",
            name="status",
            field=models.CharField(
                choices=[
                    ("ongoing", "Ongoing"),
                    ("planned", "Planned"),
                    ("released", "Released"),
                    ("suspended", "Suspended"),
                ],
                default="planned",
                max_length=30,
            ),
        ),
    ]
