# Generated by Django 4.2.2 on 2023-06-17 12:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manga", "0003_manga_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rating",
            old_name="anime",
            new_name="manga",
        ),
    ]
