# Generated by Django 4.2.2 on 2023-06-18 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("manga", "0004_rename_anime_rating_manga"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="manga",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapters",
                to="manga.manga",
            ),
        ),
        migrations.AddField(
            model_name="manga",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
    ]
