# Generated by Django 4.2.2 on 2023-06-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manga", "0005_chapter_manga_manga_view_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_parent",
            field=models.BooleanField(default=False),
        ),
    ]
