# Generated by Django 4.2.2 on 2023-06-21 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("manga", "0006_comment_is_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="manga",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pages",
                to="manga.manga",
            ),
        ),
    ]
