# Generated by Django 4.2.2 on 2023-06-23 10:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manga", "0008_ratingcomment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="rating",
        ),
    ]
