# Generated by Django 4.2.2 on 2023-06-29 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("manga", "0009_remove_comment_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="manga",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="ratingcomment",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="manga.comment",
            ),
        ),
    ]
