# Generated by Django 4.2.2 on 2023-07-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manga", "0010_chapter_slug_manga_slug_alter_ratingcomment_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RenameModel(
            old_name="Genres",
            new_name="Genre",
        ),
        migrations.RemoveField(
            model_name="volume",
            name="release_date",
        ),
        migrations.AlterField(
            model_name="chapter",
            name="title",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="manga",
            name="tag",
            field=models.ManyToManyField(blank=True, to="manga.tag"),
        ),
    ]
