# Generated by Django 4.2.2 on 2023-07-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manga", "0011_tag_rename_genres_genre_remove_volume_release_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="slug",
            field=models.SlugField(null=True),
        ),
    ]
