# Generated by Django 4.2.2 on 2023-07-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manga", "0012_alter_chapter_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="chapter_number",
            field=models.FloatField(),
        ),
    ]
