# Generated by Django 4.2.2 on 2023-07-04 09:32

from django.db import migrations, models
import manga.utils


class Migration(migrations.Migration):
    dependencies = [
        ("manga", "0013_alter_chapter_chapter_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manga",
            name="backround_image",
            field=models.ImageField(
                blank=True, upload_to=manga.utils.background_image_upload_path
            ),
        ),
    ]
